[phases.setup]
nixPkgs = [\"cmake\", \"gcc\", \"gxx\", \"portaudio\", \"openblas\", \"lapack-reference\"]

[phases.install]
cmds = [\"pip install --upgrade pip setuptools wheel\"]

[phases.build]
cmds = [\"pip install -r requirements.txt\", \"python manage.py collectstatic --no-input\"]

[start]
cmd = \"python manage.py migrate && gunicorn futurproctor.wsgi --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120\"
